version: '3.8'

services:
  nginx:
    build: ./
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./log
        target: /var/log/nginx
    networks:
      - web


networks:
  web:
    driver: bridge