ENV["VAGRANT_DEFAULT_PROVIDER"] = "docker"

Vagrant.configure("2") do |config|
  config.vm.define "mail" do |mail|
    mail.vm.network :private_network, ip: "192.168.91.5", netmask: "24"
    mail.vm.provider "docker" do |d|
      d.build_dir = "./mail-server/"
	  d.ports = ["1025:1025", "8025:8025"]
    end
  end
end