# docker-compose -f docker-compose.yml up -d
# run above command to set up the applications in docker

version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=trial
    networks:
      - elastic
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"


  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.1
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_NAME: kibana
    networks:
      - elastic
    volumes:
      - kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.1
    container_name: logstash
    restart: always
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "9600:9600"
    networks:
      - elastic
    configs:
      - source: ls_config
        target: /usr/share/logstash/pipeline/logstash.conf


  filebeat:
    command: filebeat -e -strict.perms=false
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.4.1
    networks:
      - elastic
    links:
      - logstash:logstash
    depends_on:
      - logstash
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      # This is needed for filebeat to load logs for system and auth modules
      - /var/log/:/var/log/:ro
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml



networks:
  elastic:

volumes:
  elasticsearch:
    driver: local 
  kibana:
  filebeat:

configs:
  ls_config:
    file: /logstashfile.conf
  fb_config:
    file: /filebeat.yml