# docker-compose -f docker-compose.yml up -d
# run above command to set up the applications in docker

version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: elasticsearch
    restart: always
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      xpack.monitoring.collection.enabled: true
      xpack.security.audit.enabled: true
      xpack.license.self_generated.type: trial
      http.host: 0.0.0.0
      # xpack.monitoring.elasticsearch.username: elastic
      # xpack.monitoring.elasticsearch.password: changeme
    networks:
      - elastic
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"


  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.2
    container_name: logstash
    restart: always
    environment:
      XPACK_MONITORING_ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "9600:9600"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    configs:
      - source: ls_config
        target: /usr/share/logstash/pipeline/logstash.conf


  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.2
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_NAME: kibana
    networks:
      - elastic
    volumes:
      - kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.4.2
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ./logs:/usr/share/filebeat/logs
    ports:
      - "5044:5044"
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml

    command: filebeat -e -strict.perms=false
    depends_on: 
      - elasticsearch
      - logstash
      - kibana
    links: 
      - logstash



networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch:
  kibana:
  filebeat:


configs:
  ls_config:
    file: /logstash.conf
  fb_config:
    file: /filebeat.docker.yml 

