# docker-compose -f docker-compose.yml up -d
# run above command to set up the applications in docker

version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=trial
    networks:
      - elastic
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"


  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.1
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_NAME: kibana
    networks:
      - elastic
    volumes:
      - kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.1
    container_name: logstash
    restart: always
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "9600:9600"
    networks:
      - elastic
    configs:
      - source: ls_config
        target: /usr/share/logstash/config/logstashfile.conf


  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.4.1
    networks:
      - elastic
    links:
      - logstash:logstash
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./mylog:/usr/share/filebeat/mylog
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]




networks:
  elastic:

volumes:
  elasticsearch:
    driver: local 
  kibana:

configs:
  ls_config:
    file: /logstashfile.conf