# ============================== Filebeat modules ==============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
  


 # ============================== Filebeat inputs ===============================  
filebeat.inputs:
- type: filestream
  enabled: true
  paths:  #Configure the global acquisition path, which can be distinguished according to different modules in the later stage
    - "/usr/share/filebeat/logs/*"  # Specify the path of the log file to be collected (the path of the file in the container, so we need to mount it)




# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: critical, error, warning, info, debug
logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
logging.selectors: ["*"]


# =================================== Kibana ===================================
setup.kibana:
  host: "localhost:5601"




# ================================== Outputs ===================================
# ------------------------------ Logstash Output -------------------------------
#Send output to logstash
output.logstash:
  hosts: ["logstash:5044"]



# ---------------------------- Elasticsearch Output ----------------------------
#Send output to elasticsearch
# output.elasticsearch:
#   hosts: ["localhost:9200"]


# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~