# Run this file using "vagrant up"
# use command "vagrant reload [box id/name]" everytime you make change to this file

unless Vagrant.has_plugin?("vagrant-vmware-desktop")
	system("vagrant plugin install vagrant-vmware-desktop")
	system("vagrant plugin update vagrant-vmware-desktop")
	puts "Plugin: vagrant-vmware-desktop installed, please try the command again."
	exit
end
# User is also required to manually install "Vagrant VMware Utility Installtion" when using VMware at
# https://www.vagrantup.com/docs/providers/vmware/vagrant-vmware-utility


Vagrant.configure("2") do |config|
	config.vm.define "elk" do |elk|
		elk.vm.network :private_network, ip: "192.168.91.10", netmask: "24"
		elk.vm.provision "shell", inline: "sysctl -w vm.max_map_count=262144"
		elk.vm.provider :docker do |d2|
			d2.name = "ELK"
			d2.remains_running = true
			d2.build_dir = "elk-docker"
			d2.ports = [ "5601:5601", "9200:9200", "5044:5044"]
		end	
	end
	
	
	config.vm.define "web" do |web|
		web.vm.network :private_network, ip: "192.168.91.20", netmask: "24"
		web.vm.provider :docker do |d3|
			d3.name = "webserver"
			d3.remains_running = true
			d3.build_dir = "elk-docker/nginx-filebeat"
			d3.ports = ["80:80"]
		end		
	end


	config.vm.define "Victim" do |vic|
		vic.vm.box="StefanScherer/windows_10"
		vic.vm.network :private_network, ip: "192.168.91.30",  netmask: "24"
		vic.vm.provision "shell", path:"elk-docker/windows-victim/enabled_network_discovery.ps1", privileged: true
		vic.vm.provision "file", source: "elk-docker/windows-victim/filebeat", destination: "C:/Program Files/Filebeat"
		vic.vm.provision "file", source: "elk-docker/windows-victim/winlogbeat", destination: "C:/Program Files/Winlogbeat"
		vic.vm.provision "shell", path:"elk-docker/windows-victim/install_filebeat.ps1", privileged: true
		vic.vm.provision "shell", path:"elk-docker/windows-victim/install_winlogbeat.ps1", privileged: true
		vic.vm.provider "vmware_desktop" do |vmw|
			vmw.memory = "4096"
		end
	end

	
	config.vm.define "Attacker" do |att|
		att.vm.box="kalilinux/rolling"
		att.vm.network :private_network, ip: "192.168.91.100", netmask: "24"
		att.vm.provider "vmware_desktop" do |vmw1|
			vmw1.memory = "4096"
		end
	end
	
end


