version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx_filebeat/logs
        target: /var/log/nginx  
    networks:
      elk-docker-compose_elastic:
        ipv4_address: 192.168.91.20

  filebeat:
    user: root
    container_name: nginx_filebeat
    image: docker.elastic.co/beats/filebeat:8.4.2
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      elk-docker-compose_elastic:
        ipv4_address: 192.168.91.21
    volumes:
      - ./nginx_filebeat/logs:/usr/share/filebeat/logs
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml
    command: filebeat -e -strict.perms=false
    external_links: 
      - elk-docker-compose_logstash
    stdin_open: true    

  heartbeat:
    container_name: nginx_heartbeat
    image: docker.elastic.co/beats/heartbeat:8.4.2
    restart: always 
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    volumes:
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    configs:
      - source: hb_config
        target: /usr/share/heartbeat/heartbeat.yml
    stdin_open: true 
    networks:
      elk-docker-compose_elastic:
        ipv4_address: 192.168.91.22
    external_links: 
      - elk-docker-compose_logstash


networks:
  elk-docker-compose_elastic:
    external: true


configs:
  fb_config:
    file: /vagrant/nginx_webserver/nginx_filebeat/filebeat.docker.yml
  hb_config:
    file: /vagrant/nginx_webserver/nginx_heartbeat/heartbeat.yml

