version: '3.8'

services:
  nginx:
    build: ./
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx_filebeat/logs
        target: /var/log/nginx  
    networks:
      - elk-docker-compose_elastic
      # web:
      #   ipv4_address: 192.168.91.10

  filebeat:
    user: root
    container_name: nginx_filebeat
    image: docker.elastic.co/beats/filebeat:8.4.2
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elk-docker-compose_elastic
    volumes:
      - ./nginx_filebeat/logs:/usr/share/filebeat/logs
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml
    command: filebeat -e -strict.perms=false
    external_links: 
      - elk-docker-compose_logstash
    stdin_open: true       

networks:
  elk-docker-compose_elastic:
    external: true
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 192.168.91.0/24
    #       gateway: 192.168.91.1

configs:
  fb_config:
    file: /nginx_filebeat/filebeat.docker.yml 

